### ISSUE TITLE
 No module named 'mmaction.models.losses.simclr_loss_ptv'

### ISSUE THREAD

**Issue by zwtu** [lambert-x/video-semisup#1]
Hi! When I try to reproduce the result, the following error has occurred. Is there a file missing?
```
File "/video-semisup-main/mmaction/models/losses/simclr_loss_ptv_new.py", line 7, in <module>
    from .simclr_loss_ptv import SimCLRLoss_PTV
ModuleNotFoundError: No module named 'mmaction.models.losses.simclr_loss_ptv'
```

**Comment by lambert-x** [comment]
Sorry for the bug. The missing file has been updated. Please let me know if there is any issues.

**Comment by zwtu** [comment]
Another file missing?  I don't know whether this module is used later.
```
/video-semisup-main/mmaction/models/backbones/__init__.py
line 17
from .resnet3d_droppath import ResNet3d_Droppath
```

**Comment by lambert-x** [comment]
> Another file missing? I don't know whether this module is used later.
> 
> ```
> /video-semisup-main/mmaction/models/backbones/__init__.py
> line 17
> from .resnet3d_droppath import ResNet3d_Droppath
> ```

 I have uploaded the file. It provides a version of ResNet3d with stochastic depth. The performance could be better with a droppath rate of 0.05 ~ 0.2. All the experiments in this paper do not use droppath but you could play with it.
