### ISSUE TITLE
How to get extra_modality ‘flow_xym’

### ISSUE THREAD

**Issue by zwtu** [lambert-x/video-semisup#4]
Hello, I saw `RawFrameDecode_Custom` in [`/mmaction/datasets/pipelines/custom_temporal.py`](https://github.com/lambert-x/video-semisup/blob/4687b469009a9f16c97ecc21309462bc94c4d14f/mmaction/datasets/pipelines/custom_temporal.py#L348). How should I get `flow_xym` here?

**Comment by lambert-x** [comment]
Please have a look at the latest commit.

**Comment by zwtu** [comment]
Hi, I visualized a flow_xym image. Is there something wrong？
![flow_xym_](https://user-images.githubusercontent.com/61494323/205223403-cdca14a3-e0dc-471f-9d27-881a39ca693a.jpg)

**Comment by lambert-x** [comment]
> Hi, I visualized a flow_xym image. Is there something wrong？ ![flow_xym_](https://user-images.githubusercontent.com/61494323/205223403-cdca14a3-e0dc-471f-9d27-881a39ca693a.jpg)

It is my implementation following the statement from MvPL(https://arxiv.org/abs/2104.00682). I didn't visualize a lot of samples and your sample seems good. As the order of the three channels will affect the visualizatation but not for the model, the color difference to the visualization in MvPL is acceptable. Please have a try and get the performance, the result with Flow + our framework should be close to TG + our framework.

**Comment by zwtu** [comment]
Okay, thank you. I'll try to reproduce MvPL.
