### ISSUE TITLE
Using fixmatch's baseline to process TG images does not achieve the accuracy in the paper

### ISSUE THREAD

**Issue by wwyy1234** [lambert-x/video-semisup#5]
I use fixmatch's baseline to process TG images, and the accuracy rate is only about 55%. Among them, the ucf101 dataset is processed, and 20% has labels. The training cycle is 180 epochs, where the code is based on your our_ method file. Could you tell me what the problem is?

**Comment by lambert-x** [comment]
I think you are talking about the Fixmatch baseline with TG as input. You need to modify the test pipeline to make the model test with TG but not RGB.
